pub mod perceptron;
pub mod layer;
pub mod network;
pub mod activation;
pub mod weights_init;
pub mod loss;
pub mod clipper;
pub mod optimizer;
pub mod regularization;
mod factories;
pub mod randomizer;
mod parameters;
pub mod update_strategy;
